run:
  timeout: 5m
  build-tags:
    - integration

linters-settings:
  gocyclo:
    min-complexity: 20
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/szaher/vibeboard
  mnd:
    settings:
      mnd:
        checks: argument,case,condition,operation,return,assign
        ignored-numbers: 0,1,2,3
        ignored-functions: strconv.FormatInt,strconv.ParseInt
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - hugeParam
      - unnecessaryBlock
      - exitAfterDefer
  revive:
    min-confidence: 0
    rules:
      - name: package-comments
        disabled: true
      - name: exported
        disabled: true
  lll:
    line-length: 150
  depguard:
    rules:
      main:
        deny: []

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: cmd/
      linters:
        - errcheck
    - text: "Error return value of.*Close.*is not checked"
      linters:
        - errcheck
    - text: "should have comment"
      linters:
        - revive
  exclude-use-default: true
  max-issues-per-linter: 0
  max-same-issues: 0

severity:
  default-severity: error