apiVersion: v1
kind: Service
metadata:
  name: {{ include "vibe-arcade.fullname" . }}-backend
  labels:
    {{- include "vibe-arcade.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vibe-arcade.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend